// Define an array of projects as JSON objects
const projectsData = [
    {
        title: "Personal Website",
        subtitle: "Personal project",
        date: "Sep 2023 - PRESENT",
        images: ["Website_0"],
        description: "Built this website from scratch using HTML, CSS, and JavaScript. Hosted on GitHub Pages.",
        skills: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
        links_text: ["See project files on GitHub"],
        links: ["https://github.com/wiltonfs/wiltonfs.github.io"],
    },
    {
        title: "Astronomy Research",
        subtitle: "UBC Computer Science Department",
        date: "May 2023 - Sep 2023",
        images: ["AstroAI_0", "AstroAI_1"],
        description: "",
        skills: ["Python", "PyTorch", "Machine learning", "High-performance computing"],
        links_text: ["See project files on GitHub"],
        links: ["https://github.com/wiltonfs/astro_research"],
    },
    {
        title: "Machine Learning Course Projects",
        subtitle: "UBC Computer Science 330",
        date: "Jan 2023 - May 2023",
        images: ["330_0", "330_1"],
        description: "Machine learning projects for CPSC 330.",
        skills: ["Python", "SciKit-Learn", "Machine learning"],
        links_text: ["See project files on GitHub"],
        links: ["https://github.com/wiltonfs/cpsc330-FW"],
    },
    {
        title: "Digital Systems and Microcomputers Course Projects",
        subtitle: "UBC Computer Engineering 312",
        date: "Jan 2023 - May 2023",
        images: ["312_0", "312_1"],
        description: "VHDL and assembly projects for CPEN 312.",
        skills: ["VHDL", "Assembly", "8051 Microprocessor", "Microcontrollers", "FPGAs"],
        links_text: ["See project files on GitHub"],
        links: ["https://github.com/wiltonfs/CPEN-312"],
    },
    {
        title: "Photogrammetry Accuracy Investigation",
        subtitle: "Craig Hospital",
        date: "May 2021 - Aug 2021",
        images: ["Craig_0", "Craig_1", "Craig_2"],
        description: "",
        skills: ["Python", "OpenCV", "Matlab", "Photogrammetry", "3D scanning", "3D printing", "Documentation"],
        links_text: [],
        links: [],
    },
    
    
];
